
--DATA CLEANING steps
--looking for duplicates
--standardizing the data(checking for spelling mistakes and others)
--checking for nulls and blank values
--removing any unnecessary clums and rows

select * from
customer_shopping_behavior

select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'customer_shopping_behavior'


--renaming the column names to snakes for more easy calling n others
EXEC sp_rename 'customer_shopping_behavior.Customer ID', 'customer_id', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Age', 'age', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Gender', 'gender', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Item Purchased', 'item_purchased', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.purchase_amouunt(usd)', 'purchase_amount', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Location', 'location', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Size', 'size', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Color', 'color', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Season', 'season', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Review Rating', 'review_rating', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Subscription Status', 'subscription_station', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Shipping Type', 'shipping_type', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Discount Applied', 'discount_applied', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Promo Code Used', 'promo_code', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Previous Purchases', 'previous_purchase', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.Payment Method', 'payment_method', 'COLUMN';
EXEC sp_rename 'customer_shopping_behavior.ffrequency_of_purchase', 'frequency_of_purchase', 'COLUMN';

--verify the chances in col_name
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'customer_shopping_behavior'

--checking for duplicate
SELECT customer_id, COUNT(*) AS DuplicateCount
FROM customer_shopping_behavior
GROUP BY customer_id
HAVING COUNT(*) > 1;

--trimming the cols
UPDATE customer_shopping_behavior
SET gender = TRIM(gender),
	item_purchased = TRIM(item_purchased),
	category = TRIM(category)

select * from
customer_shopping_behavior

SELECT 
    COUNT(*) AS TotalRows,
    COUNT(customer_id) AS customer_id_NotNull,
    COUNT(age) AS Age_NotNull,
    COUNT(gender) AS Gender_NotNull,
    COUNT(category) AS category_NotNull,
    COUNT(purchase_amount) AS purchase_amount_NotNull,
    COUNT(location) AS location_NotNull,
    COUNT(color) AS color_NotNull,
    COUNT(season) AS season_NotNull,
    COUNT(review_rating) AS review_rating_NotNull,
    COUNT(subscription_station) AS subscription_station_NotNull,
    COUNT(shipping_type) AS shipping_type_NotNull,
    COUNT(discount_applied) AS discount_applied_NotNull,
    COUNT(promo_code) AS promo_code_NotNull,
    COUNT(previous_purchase) AS previous_purchase_NotNull,
    COUNT(payment_method) AS payment_method_NotNull,
    COUNT(frequency_of_purchase) AS frequency_of_purchase_NotNull
FROM customer_shopping_behavior

--from the return count value of review_rating, there are some missing values
select *
    from customer_shopping_behavior
    where review_rating is null

--adding a new col(age_group)
ALTER TABLE customer_shopping_behavior
ADD age_group varchar(20);

select min(age), avg(age), max(age)
from customer_shopping_behavior

--populating the col based on the age range
UPDATE customer_shopping_behavior
SET age_group = CASE
    WHEN age BETWEEN 18 AND 25 THEN '18-25'
    WHEN age BETWEEN 26 AND 35 THEN '26-35'
    WHEN age BETWEEN 36 AND 45 THEN '36-45'
    WHEN age BETWEEN 46 AND 60 THEN '46-60'
    ELSE '60+'
END;

--comparing the data of discount and promo.. checking to remove redundancy
SELECT *
FROM customer_shopping_behavior
WHERE discount_applied = promo_code;

--this comparison flag help give indicator for each role, therefore, there's redundancy
SELECT 
    customer_id,
    discount_applied,
    promo_code,
    CASE 
        WHEN discount_applied = promo_code THEN 'Match'
        ELSE 'Mismatch'
    END AS ComparisonResult
FROM customer_shopping_behavior;

--moving the redundancy col. promo_code
ALTER TABLE customer_shopping_behavior
DROP COLUMN promo_code


select * from 
customer_shopping_behavior


--•	What’s the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as generate_rev
    from customer_shopping_behavior
    group by gender
    order by generate_rev


--•	Which customers used a discount buh still spend than the average purchase amount?
select customer_id, discount_applied, purchase_amount
    from customer_shopping_behavior
    where discount_applied = 'Yes' and purchase_amount >= 
                                            (select avg(purchase_amount) from 
                                                customer_shopping_behavior)

--•	Which are the top 5 products with the highest average review ratings?
select TOP 5 item_purchased, avg(review_rating) as Avg_rating
    from customer_shopping_behavior
    group by item_purchased
    order by Avg_rating desc


--•	Compare the average purchase amounts  btn standard and express shipping
select shipping_type, Round(avg(purchase_amount), 2) as Avg_Purchase_amount
    from customer_shopping_behavior
    where shipping_type In ('Standard', 'Express')
    group by shipping_type

--•	Do subscribed customers spend more?  Compare avg spend and total revenue btn subcribers and non-subscribers
SELECT 
    subscription_station,
    COUNT(DISTINCT customer_id) AS customer_count,
    AVG(purchase_amount) AS avg_spend_per_customer,
    SUM(purchase_amount) AS total_revenue
    from customer_shopping_behavior
    group by subscription_station
    order by  total_revenue, avg_spend_per_customer desc


--•	Which 5 products have the highest percentage of purchase with discounts applied?
            --to get percentage, multiply by 100.0 
select TOP 5 item_purchased,
count(Case
        when discount_applied is not null then 1 end)*100.0 /count(*) as purchased_discount_item
   from customer_shopping_behavior
   group by item_purchased
   order by purchased_discount_item desc

--•	Segment customers into new, returning, and  loyal based on their total number of previous purchase and show the count of each segment.
select * from 
customer_shopping_behavior

WITH customer_stance AS (
Select customer_id, previous_purchase,
    Case 
        WHEN previous_purchase = 1 THEN 'New'
        WHEN previous_purchase BETWEEN 2 AND 15 THEN 'Returning'
        ELSE 'Loyal'
    End AS customer_segment
    from customer_shopping_behavior
    )
    select customer_segment, count(*) as cust_count
    from customer_stance
    group by customer_segment
    order by cust_count
    
 --•	What are the top 3  most purchased products within each category?
 select TOP 3 item_purchased, category
     from customer_shopping_behavior
     group by item_purchased
     order by category desc

WITH ProductCounts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS product_rank
    FROM customer_shopping_behavior
    GROUP BY category, item_purchased
)
SELECT product_rank, category, item_purchased, purchase_count
FROM ProductCounts
WHERE product_rank <= 3
ORDER BY category, purchase_count DESC;


--•	Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_station,
count(*) as repeat_buyers
from customer_shopping_behavior
where previous_purchase > 5
group by subscription_station


--•	What is the revenue contribution of each age?
select age_group,
    sum(purchase_amount) as total_rev
    from customer_shopping_behavior
    group by age_group
    order by total_rev desc



